### ISSUE TITLE
Kubeturbo Operator's CRD requires update to apiextensions version to support k8s 1.22+

### ISSUE THREAD

**Issue by evat-pm** [turbonomic/kubeturbo#603] opened 2021-09-13 14:16 UTC
The CRD for the operator uses apiVersion: apiextensions.k8s.io/v1beta1 and this is officially deprecated in k8s 1.22
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#customresourcedefinition-v122.

This will cause this CRD are related operator to not deploy into any kubernetes cluster v1.22 or higher.

Need to update the apiextensions to v1 and update related schema, validations.

**Comment by esara** [comment] 2021-09-14 00:47
duplicate of https://github.com/turbonomic/kubeturbo/issues/597

**Closed by esara** 2021-09-14 00:47 UTC
